<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Vale.Tops.Integration.OpcDaDriver.Wpf</RootNamespace>
    <AssemblyName>Vale.Tops.Integration.OpcDaDriver.Wpf</AssemblyName>
    <UseWPF>true</UseWPF>
    <Platforms>x86</Platforms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Prefer32Bit>true</Prefer32Bit>
  </PropertyGroup>
  <ItemGroup>
    <COMReference Include="stdole">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>2</VersionMajor>
      <Guid>00020430-0000-0000-c000-000000000046</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
    <COMReference Include="OPCAutomation">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>28e68f91-8d75-11d1-8dc3-3c302a000000</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Vale.Tops.Domain\Vale.Tops.Domain.csproj" />
    <ProjectReference Include="..\..\Vale.Tops.Integration.Infrastructure.DataBase\Vale.Tops.Integration.Infrastructure.DataBase.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Web" />
  </ItemGroup>
</Project>
